import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans, Public_Sans } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSans = Noto_Sans({ subsets: ["latin"], variable: "--font-noto-sans", weight: ["400", "500", "700", "900"] });
const publicSans = Public_Sans({ subsets: ["latin"], variable: "--font-public-sans", weight: ["400", "500", "700", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoSans.variable} ${publicSans.variable} antialiased`}>
        <div className="relative flex size-full min-h-screen flex-col bg-white overflow-x-hidden">
          <div className="layout-container flex h-full grow flex-col">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
